### ISSUE TITLE
TypeScript language service doesn't like imports without ".vue"

### ISSUE THREAD

**Issue by pauleveritt** [wallabyjs/wallaby-934#1]
I'm using WebStorm 2017 EAP. hello.spec.ts gives a TypeScript error:

`Error:(2, 17) TS2307:Cannot find module '../src/App'.`

...when cloned directly. If I change it to:

`import App from '../src/App.vue'`

...it works.

Note: I'm the JetBrains dev advocate that covers WebStorm. I'm kind of working on some thoughts for a blog post about TDD with Wallaby, so I'll be asking some minor questions, to make sure I explain things right.

**Comment by pauleveritt** [comment]
Also, appending ".vue" doesn't fix it unless tsconfig.json changes from the existing:

`
  "include": [
    "src/**/*.ts"
  ]
`

...to an exclude of node_modules etc.

**Comment by ArtemGovorov** [comment]
Hi Paul, 

I'll be looking into this one shortly. Happy to answer any other questions as well. 

Please note that Vue support (especially with TypeScript) in wallaby is something very new and still experimental. We have only just recently started to get requests to support Vue. What I'm trying to say is that perhaps Vue support specifically is not the best topic for the blog post about TDD with Wallaby, as it's still early stages and many things are likely to change.

**Comment by pauleveritt** [comment]
Ok, makes sense, I’ll postpone working on a blog post.

Would you prefer that I not file these kinds of very-minor tickets while you’re still working on it?

—Paul

**Comment by ArtemGovorov** [comment]
> Would you prefer that I not file these kinds of very-minor tickets while you’re still working on it?

Please do submit them, they are every helpful and will get us to support Vue faster.

**Comment by ArtemGovorov** [comment]
Updated the `tsconfig.json` to get rid of the error.
