### ISSUE TITLE
WebStorm-friendly <script> in .vue

### ISSUE THREAD

**Issue by pauleveritt** [wallabyjs/wallaby-934#4]
Instead of:

`<script lang="ts">`

...perhaps:

`<script lang="ts" type="typescript">`

As a side note, if I omit `lang="ts"` then Wallaby gets mad:

`Error: Cannot find module "!!!vue-loader/lib/selector?type=script&index=0!./App.vue"`

But I can't find anything in the webpack configuration files that activates "type=script". Perhaps that's built into Wallaby itself.

**Comment by ArtemGovorov** [comment]
Added `type="typescript"`.
Re: `lang="ts"`, this is not something that is wallaby.js related (wallaby doesn't even process the contents of `.vue` files yet). As far as I remember, `lang="ts"` is something that `vue-loader` is using to correctly compile it.

**Comment by pauleveritt** [comment]
Ah, perhaps I misunderstood then. When you say Wallaby doesn’t process the contents of .vue, does that mean I should be using it yet for test running of components defined in a .vue <script>?

—Paul

**Comment by ArtemGovorov** [comment]
> Wallaby doesn’t process the contents of .vue, does that mean I should be using it yet for test running of components defined in a .vue <script>?

You should be able to use wallaby to test components in .vue files, it's just that wallaby will not display covergae indicators inside .vue file <script> section.
